services:

  zookeeper:
    container_name: zookeeper
    extends:
      file: kafka-compose.yaml
      service: zookeeper
  broker:
    container_name: broker
    extends:
      file: kafka-compose.yaml
      service: broker

networks:
  default:
    name: debs-network