services:

  zookeeper:
    container_name: zookeeper
    extends:
      file: kafka-compose.yaml
      service: zookeeper
  kafka:
    container_name: kafka
    extends:
      file: kafka-compose.yaml
      service: kafka

networks:
  default:
    name: debs-network