x-spark-common: &spark-common
  image: nmngo248/spark:3.5.0
  environment: &spark-common-env
    SPARK_MASTER_HOST: spark-master
    SPARK_MASTER_PORT: 7077
    SPARK_MASTER_WEBUI_PORT: 8080
    SPARK_PUBLIC_DNS: localhost
    SPARK_RPC_AUTHENTICATION_ENABLED: "no"
    SPARK_RPC_ENCRYPTION_ENABLED: "no"
    SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: "no"
    SPARK_SSL_ENABLED: "no"
  volumes:
    - ./spark/app:/opt/bitnami/spark/app
    - ./spark/resources:/opt/bitnami/spark/resources
services:
  spark-master:
    <<: *spark-common
    hostname: spark-master
    container_name: spark-master
    ports:
      - "8080:8080"
    environment:
      <<: *spark-common-env
      SPARK_MODE: master